In [2]:
notes = ['c','d','e']
melody = []
prob = [0.1, 0.4, 0.5]
import numpy as np


In [7]:
for i in range(30):
    note = np.random.multinomial(1,prob)
    melody.append(notes[np.where(note)[0][0]])

print(melody)

['e', 'd', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'd', 'e', 'e', 'd', 'd', 'e', 'e', 'd', 'd', 'd', 'c', 'e', 'e', 'd', 'd', 'e', 'd', 'e', 'd', 'd', 'e']


In [10]:
import music21 as mus
tn = 'tinyNotation: ' + " ".join (melody)

s = mus.converter.parse(tn)
s.show('midi')

In [9]:
s.show('midi')

In [11]:
tran = np.array([[0.4, 0.1, 0.5], [0.3, 0.3, 0.4], [0.7, 0.2, 0.1]])
start = np.array([1,0,0])

In [12]:
print(tran)

[[ 0.4  0.1  0.5]
 [ 0.3  0.3  0.4]
 [ 0.7  0.2  0.1]]


In [13]:
prob = np.dot(start,tran)
print(prob)

[ 0.4  0.1  0.5]


In [15]:
state = np.random.multinomial(1,prob)
print (state)

[1 0 0]


In [16]:
state = start
mel = []
for i in range(30):
    prob = np.dot(start,tran)
    state = np.random.multinomial(1,prob)
    mel.append(notes[np.where(state)[0][0]])
    

In [17]:
tn = 'tinyNotation: ' + " ".join(mel)

s = mus.converter.parse(tn)
s.show()

SubConverterException: Cannot find a path to the 'mscore' file at /Applications/MuseScore 2.app/Contents/MacOS/mscore -- download MuseScore